### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by ramonrails** [atom/background-tips#23]
[Enter steps to reproduce below:]
1. opened markdown file, preview was showing
2. font was proportional, changed to monaco fixed width
3. closed markdown file without edit. bam! error! :)

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package, v0.26.0
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120

TypeError: Cannot read property 'classList' of undefined
    at background-tips.module.exports.BackgroundTipsElement.showNextTip (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120:19)
    at background-tips.module.exports.BackgroundTipsElement.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:94:12)
    at background-tips.module.exports.BackgroundTipsElement.updateVisibility (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:77:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:42:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:560:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:462:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MarkdownPreviewEditor.detached (/Users/ram/.atom/packages/atom-markdown-katex/lib/md-preview-editor.coffee:231:14)
    at space-pen-div.View.element.detached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:167:63)
    at space-pen-div.CustomElementPrototype.detachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:55:55)
    at atom-pane-axis.PaneAxisElement.childRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:83:19)
    at atom-pane-axis.PaneAxisElement.childReplaced (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:92:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:200:27)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:188:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:832:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:823:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:584:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "highlight-column",
      "indent-guide-improved",
      "tree-view-git-status",
      "linter-ruby-reek",
      "rails-model-schema",
      "linter-ruby",
      "markdown-preview",
      "markdown-pdf",
      "markdown-preview-plus",
      "markdown-scroll-sync",
      "wrap-guide",
      "autocomplete-python",
      "autocomplete-ruby",
      "copy-as-rtf",
      "css-edit-groups",
      "css-to-inline",
      "ex-mode",
      "fonts",
      "git-control",
      "line-diff-details",
      "pdf-view",
      "react",
      "ruby-bundler"
    ],
    "projectHome": "/Users/ram/work/projects",
    "themes": [
      "native-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.22.0
aligner-ruby, v1.4.0
atom-everydayrails-rspec, v0.4.0
atom-markdown-katex, v0.5.6
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.9.1
coffee-compile, v0.21.1
color-picker, v2.1.1
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
emmet, v2.4.3
file-icons, v1.7.8
formatter-coffeescript, v0.1.1
git-diff-details, v1.3.0
go-to-view, v0.3.0
javascript-snippets, v1.2.1
jsformat, v0.9.3
jshint, v1.8.5
language-javascript-semantic, v0.2.1
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-jshint, v2.1.0
markdown-table-formatter, v2.8.3
merge-conflicts, v1.4.2
native-ui, v0.17.0
pigments, v0.26.0
project-manager, v2.9.7
rails-i18n, v0.1.3
rails-i18n-autocomplete, v0.3.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-syntax-replacer, v0.5.1
ruby-test-switcher, v1.2.1
tab-numbers, v0.3.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@ramonrails Can you reproduce this in safe mode (`atom --safe`)?

**Comment by ramonrails** [comment]
Will do it over the weekend.

Regards, Ram

**Comment by ramonrails** [comment]
tested. —safe mode has no markdown preview. works fine.

> On 29-Apr-2016, at 9:16 PM, Wliu <notifications@github.com> wrote:
> 
> @ramonrails <https://github.com/ramonrails> Can you reproduce this in safe mode (atom --safe)?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/atom/background-tips/issues/23#issuecomment-215768874>

Regards, Ram
---
Making things simple.

+91-95606-33544
ramonrails @ hangout/gtalk, Skype, github, linkedin, YIM, MSN, twitter, facebook
http://www.ramonrails.in <http://www.ramonrails.in/>
_______________________________________________________________________________________
Notice: This e-mail (and any attachments), is confidential and may be privileged. It may be read, copied and used only by intended recipients. Unauthorized access to this e-mail (or attachments) and disclosure or copying of its contents or any action taken in reliance on it is unlawful. Unintended recipients must notify the sender immediately by e-mail/phone & delete it from their system without making any copies or disclosing it to a third person.

**Comment by ramonrails** [comment]
repeating now consistently, every time. 
1. keep atom open (normal mode)
2. double click .md file to open it (preview shows)
3. command-w to close the .md file

**Comment by ramonrails** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package, v0.26.0


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120

TypeError: Cannot read property 'classList' of undefined
    at background-tips.module.exports.BackgroundTipsElement.showNextTip (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120:19)
    at background-tips.module.exports.BackgroundTipsElement.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:94:12)
    at background-tips.module.exports.BackgroundTipsElement.updateVisibility (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:77:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:42:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:560:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:462:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MarkdownPreviewEditor.detached (/Users/ram/.atom/packages/atom-markdown-katex/lib/md-preview-editor.coffee:231:14)
    at space-pen-div.View.element.detached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:167:63)
    at space-pen-div.CustomElementPrototype.detachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:55:55)
    at atom-pane-axis.PaneAxisElement.childRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:83:19)
    at atom-pane-axis.PaneAxisElement.childReplaced (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:92:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:200:27)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:188:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:832:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:823:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:584:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:617:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:692:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:731:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:211:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.4.0 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "highlight-column",
      "indent-guide-improved",
      "tree-view-git-status",
      "linter-ruby-reek",
      "rails-model-schema",
      "linter-ruby",
      "markdown-preview",
      "markdown-pdf",
      "markdown-preview-plus",
      "markdown-scroll-sync",
      "wrap-guide",
      "autocomplete-python",
      "autocomplete-ruby",
      "copy-as-rtf",
      "css-edit-groups",
      "css-to-inline",
      "ex-mode",
      "fonts",
      "git-control",
      "line-diff-details",
      "pdf-view",
      "react",
      "ruby-bundler"
    ],
    "projectHome": "/Users/ram/work/projects",
    "themes": [
      "native-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.22.0
aligner-ruby, v1.4.0
atom-everydayrails-rspec, v0.4.0
atom-markdown-katex, v0.5.6
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.9.1
coffee-compile, v0.21.1
color-picker, v2.1.1
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
emmet, v2.4.3
file-icons, v1.7.8
formatter-coffeescript, v0.1.1
git-diff-details, v1.3.0
go-to-view, v0.3.0
javascript-snippets, v1.2.1
jsformat, v0.9.3
jshint, v1.8.5
language-javascript-semantic, v0.2.1
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-jshint, v2.1.0
markdown-table-formatter, v2.8.3
merge-conflicts, v1.4.2
native-ui, v0.17.0
pigments, v0.26.0
project-manager, v2.9.7
rails-i18n, v0.1.3
rails-i18n-autocomplete, v0.3.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-syntax-replacer, v0.5.1
ruby-test-switcher, v1.2.1
tab-numbers, v0.3.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by shaohailong** [comment]
it happens with me too

**Comment by shaohailong** [comment]
[Enter steps to reproduce below:]

1. edit 2 md file
2. use cmd+W to close md files
3. when i use cmd+W to close the last md file, see this error

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package, v0.26.0


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120

TypeError: Cannot read property 'classList' of undefined
    at background-tips.module.exports.BackgroundTipsElement.showNextTip (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:120:19)
    at background-tips.module.exports.BackgroundTipsElement.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:94:12)
    at background-tips.module.exports.BackgroundTipsElement.updateVisibility (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:77:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/background-tips/lib/background-tips-view.js:42:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:560:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:462:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MarkdownPreviewEditor.detached (/Users/lucas/.atom/packages/atom-markdown-katex/lib/md-preview-editor.coffee:242:14)
    at space-pen-div.View.element.detached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:167:63)
    at space-pen-div.CustomElementPrototype.detachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:55:55)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container-element.js:38:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:165:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:175:19)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:188:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:832:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:823:39)
```

### Commands

```
  2x -0:01.7.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "typewriter-sounds",
      "file-icons",
      "emmet",
      "tidy-markdown",
      "markdown-format"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-markdown-katex, v0.5.9
markdown-image-helper, v1.0.4
pigments, v0.26.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This seems like it has been fixed.
