### ISSUE TITLE
Failed to load the background-tips package / override purpose

### ISSUE THREAD

**Issue by mostafa6765** [atom/background-tips#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package 0.27.1

### Stack Trace

Failed to load the background-tips package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/background-tips-master/lib/background-tips-view.coffee:1:5)
    at /packages/background-tips-master/lib/background-tips-view.coffee:1:1)
    at /packages/background-tips-master/lib/background-tips-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/background-tips-master/lib/background-tips.coffee:1:22)
    at /packages/background-tips-master/lib/background-tips.coffee:1:1)
    at /packages/background-tips-master/lib/background-tips.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:144:18)
```

### Commands

```
     -0:29.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:02.7.0 editor:newline (input.hidden-input)
     -0:01.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-bulma 0.7.0 
atom-ide-ui 0.4.0 
atom-lara 0.3.0 
atom-music 0.7.0 
blade-spacer 0.4.2 
dev 0.5.0 
devtheme 0.4.0 
file-icons 2.1.12 
highlight-selected 0.13.1 
ide-php 0.6.9 
language-blade 0.36.0 
language-vue 0.23.1 
minimap 4.29.7 
platformio-ide-terminal 2.7.0 
pure-syntax 0.3.0 
single-click-open 0.2.2 
structure-view 0.1.4 
```

**Comment by mostafa6765** [comment]
solved . by npm install
