### ISSUE TITLE
Failed to activate the background-tips package

### ISSUE THREAD

**Issue by ryanmohta** [atom/background-tips#42]
**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.5
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package 0.28.0

### Stack Trace

Failed to activate the background-tips package

```
At Error processing argument at index 0, conversion failure from [object Array]
TypeError: Error processing argument at index 0, conversion failure from [object Array]
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:211:31)
    at Array.map (<anonymous>)
    at unwrapArgs (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:233:15)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:350:12)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

Error: Error processing argument at index 0, conversion failure from [object Array]
TypeError: Error processing argument at index 0, conversion failure from [object Array]
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:211:31)
    at Array.map (<anonymous>)
    at unwrapArgs (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:233:15)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:350:12)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at new BackgroundTipsElement (/Applications/Atom.app/Contents/Resources/app/node_modules/background-tips/lib/background-tips-view.js:39:35)
    at Object.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/background-tips/lib/background-tips.js:5:37)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - did this error show up right after updating to 1.28.2 (or was 1.28.2 your first install of Atom)?  And are you getting this error repeatedly just by starting Atom?

**Comment by rsese** [comment]
Oh also, I'm not sure if the error reporter is correct that you have no community packages installed, but do you see the error in safe mode (`atom --safe`)?

**Comment by ryanmohta** [comment]
@rsese I got the error right after upgrading to 1.28.2. The interesting thing is, I only got this error the first time I opened Atom after upgrading. The subsequent times, I don't see the error, and the background tips display fine once closing all the editor windows. I am not sure how to check for the error in safe mode, could you let me know how to do that?

**Comment by rsese** [comment]
> I got the error right after upgrading to 1.28.2. The interesting thing is, I only got this error the first time I opened Atom after upgrading. The subsequent times, I don't see the error, and the background tips display fine once closing all the editor windows.

Ahhh ok thanks for the details :+1:

> I am not sure how to check for the error in safe mode, could you let me know how to do that?

On macOS you can open Terminal and run that command:

```
atom --safe
```

[Safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) is helpful to test if a community package might be causing/related to a particular issue that you're seeing.

Since you only saw this error once and it's not reproducible, we'll go ahead and close for now but we can re-open later if necessary.

**Comment by deathbybandaid** [comment]
I've had this error as of the past week.

````
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package 0.28.0


### Stack Trace

Failed to activate the background-tips package

```
At Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (C:\Users\Administrator\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)


Error: Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at new BackgroundTipsElement (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:663937)
    at Object.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:167394)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3541396)
    at measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540808)
    at Package.measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3538418)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540668)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540611)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381612)
    at config.transactAsync (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381228)
    at Config.transactAsync (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:331162)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381178)
    at PackageManager.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:380728)
    at t.loadState.then (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:734978)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-powersnap 0.1.4 
autocomplete-python 1.14.1 
autocomplete-python-jedi 1.10.3-0 
awesome-python-snippets 0.3.0 
busy-signal 2.0.1 
docblock-python 0.15.0 
file-icons 2.1.34 
filesize 4.0.4 
highlight-selected 0.16.0 
intentions 1.1.5 
kite 0.168.0 
language-aiml 0.3.0 
language-powershell 5.0.0 
lint-scroll-marker 0.3.0 
linter 2.3.1 
linter-bootlint 1.1.6 
linter-htmlhint 1.6.2 
linter-htmllint 1.1.5 
linter-jsonlint 1.4.0 
linter-just-say-no 0.7.5 
linter-pylama 0.10.1 
linter-shellcheck 1.6.0 
linter-tidy 2.4.0 
linter-ui-default 1.7.1 
linter-ui-plus 0.3.2 
linter-write-good 0.9.2 
linter-xmllint 1.4.4 
MagicPython 1.1.1 
multi-wrap-guide 1.1.8 
pane-browser 1.6.0 
pdf-view 0.71.0 
pinned-tabs 2.1.1 
python-black 0.7.0 
python-docstring 0.0.3 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-requirements 0.2.1 
python-yapf 0.14.0 
reindent 1.5.0 
runtime-info-atom 1.0.0 
scroll-marker 0.3.2 
sync-settings 0.8.6 
TabNine 0.1.5 
tabs-to-spaces 1.0.5 
teletype 0.13.4 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.5.2 
typewriter 0.8.0 
wordcount 3.1.0 
````

**Comment by brett8883** [comment]
I just had the same issue
          
Failed to activate the background-tips package

Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)
Hide Stack Trace
Error: Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:271:17)
    at Object.exception (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219:30)
    at metaToValue (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:223:28)
    at Object.remoteMemberFunction (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:123:16)
    at new BackgroundTipsElement (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:664930)
    at Object.activate (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:167477)
    at Package.activateNow (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405731)
    at measure (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405143)
    at Package.measure (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405003)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3404946)
    at PackageManager.activatePackage (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:382285)
    at config.transactAsync (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381901)
    at Config.transactAsync (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:331549)
    at PackageManager.activatePackages (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381851)
    at PackageManager.activate (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381401)
    at t.loadState.then (C:\Users\Brett\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:1:736497)

**Comment by stanavov** [comment]
And I have the same error after every atom start. But it appears only if atom starts with no tabs.
