### ISSUE TITLE
Failed to activate the background-tips package

### ISSUE THREAD

**Issue by kaiyoma** [atom/background-tips#46]
This error and stack trace have started appearing recently (several times) while I've been using using Atom:

```
Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

Error: Cannot call function 'on' on missing remote object 1
Error: Cannot call function 'on' on missing remote object 1
    at throwRPCError (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:271:17)
    at Object.exception (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219:30)
    at metaToValue (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:223:28)
    at Object.remoteMemberFunction (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:123:16)
    at new BackgroundTipsElement (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:664930)
    at Object.activate (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:167477)
    at Package.activateNow (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405731)
    at measure (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405143)
    at Package.measure (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3402753)
    at activationPromise.activationPromise.Promise (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3405003)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:3404946)
    at PackageManager.activatePackage (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:382285)
    at config.transactAsync (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381901)
    at Config.transactAsync (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:331549)
    at PackageManager.activatePackages (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381851)
    at PackageManager.activate (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:381401)
    at t.loadState.then (C:\Users\Kyle Getz\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:1:736497)
```

OS: Windows 10
Atom: 1.40.1
Package: 0.28.0

**Comment by rsese** [comment]
Thanks for the report - do you happen to have specific steps to reproduce?  Also, if you see the error often, can you confirm if you see the error in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

x-ref: https://github.com/atom/atom/issues/16630

**Comment by kaiyoma** [comment]
Unfortunately, it pops up randomly and I don't have any repro steps. I've seen it happen twice in the last week, but I had never seen it during the prior 3-4 months that I've been using Atom. ¯\\\_(ツ)_/¯

**Comment by rsese** [comment]
Do you happen to remember if you see the error in particular when you've switched focus to some other program and then back to Atom (by alt-tabbing away and back to Atom for example)?

**Comment by kaiyoma** [comment]
No, I think it happened after closing the last open file.

**Comment by gt2280** [comment]
For me it happened immediately on starting up Atom after not using it for a
week.

**Comment by lamansky** [comment]
It just started happening for me today, every time I open a new Atom window.

**Comment by 21CS** [comment]
For me it happened upon installation on a new machine.

**Comment by kaiyoma** [comment]
Just got it again when opening Atom. No previous Atom processes were running and I had no previously open files.

**Comment by softwarecreations** [comment]
I just experienced this issue now. I closed Atom and reopened it and it didn't happen again.
Seems similar to another issue that I recently experienced.
https://github.com/atom/github/issues/2244

This is the first time I've experienced this issue.
I did not make any changes/updates to Atom or my system whatsoever since the last time I used Atom.

I'm running Atom 1.40.1 x64 On Debian 10 Kernel 5.0.21

**Comment by rsese** [comment]
For anyone that sees this error consistently, curious if you can reproduce with the current [beta](https://atom.io/beta)?  I wonder if this is related to an Electron issue that's been fixed and the current beta is on Electron 4.2.7 versus Atom 1.40.1 which is on Atom 3.1.10.

**Comment by JesseMMendez** [comment]
I opened Atom from it's downloaded exe file, until I found the App in my user folder, made a shortcut to desktop, opened it and got the message

**Comment by rsese** [comment]
Is that with Atom Beta?

**Comment by StevieboyExpress** [comment]
First time I'm seeing this. I just installed a bunch of packages for the first time. not sure if this helps.

**Comment by Matt-Warnock** [comment]
Just happened to me for the first time for no (aparrant) reason.

**Comment by startryst** [comment]
me too

**Comment by jlbiahdev** [comment]
same

**Comment by iamh2o** [comment]
Happening for me too.


1. start up atom from double click osc app icon

**Atom**: 1.58.0-beta0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [background-tips](https://github.com/atom/background-tips) package 0.28.0


### Stack Trace

Failed to activate the background-tips package

```
At Image could not be created from /Users/jmajor/.atom/packages/atoms-touchbar/icons/undefined.png

Error: Image could not be created from /Users/jmajor/.atom/packages/atoms-touchbar/icons/undefined.png


```

### Commands

```
```

### Non-Core Packages

```
acid-syntax 1.0.0 
acido-syntax 0.2.1 
advanced-open-file 0.16.8 
atom-clock 0.1.18 
atom-commander 0.12.3 
atom-distraction-free-ui-theme 2.1.0 
atom-drawio 1.15.0 
atom-html-preview 0.2.6 
atom-hydra 0.3.2 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-notes 1.23.0 
atom-sync 0.7.3 
atom-toolbar-preferred 1.4.1 
atoms-touchbar 0.4.0 
breakdown 0.90.6 
busy-signal 2.0.1 
data-atom 0.29.1 
data-explorer 0.7.0 
emacs-plus 0.12.0 
emacs-tab 0.2.0 
firacode 0.3.0 
ftp-remote-edit-plus 1.3.1 
git-control-fork 0.11.0 
git-projects-manager 1.0.0 
Hydrogen 2.16.3 
hydrogen-auth 0.0.2 
hydrogen-cell-separator 0.4.1 
hydrogen-exectime 0.8.0 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
hydrogen-run 0.1.10 
hydrogen-xdbg 0.0.4 
hyper-alien-ui-theme 0.4.0 
intentions 2.1.1 
ipython-exec 1.2.0 
ipython-run 0.3.1 
kite 0.206.0 
language-atom-notes 0.4.1 
language-r 0.4.2 
linter 3.4.0 
linter-coffeelint 2.0.75 
linter-csslint 2.0.6 
linter-flake8 2.4.0 
linter-htmllint 1.1.14 
linter-js-yaml 1.4.6 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-lintr 1.2.0 
linter-shellcheck 1.6.0 
linter-ui-default 3.4.1 
markdown-cell-highlight 1.2.0 
minimap 4.39.14 
minimap-lens 0.8.2 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
moments-atom 0.2.0 
no-compromise-ui 0.1.2 
node_modules undefined 
northem-light-atom-ui 2.1.1 
one-dark-syntax-colors-of-the-year-pantone 2.1.0 
organized 0.8.1 
pigments 0.40.6 
project-manager 3.3.8 
python-black 0.7.0 
r24y-touch-bar 0.3.0 
remote-ftp 2.2.4 
sequence-diagram 0.0.2 
slack-chat 3.4.2 
space-fleet-syntax 1.0.0 
that-syncing-feeling 0.2.0 
theme-alien-syntax 0.6.0 
tool-bar 1.4.4 
tool-bar-almighty 0.9.0 
tool-bar-atom 1.7.1 
tool-bar-markdown 1.0.5 
touchbar-plus 0.3.1 
touchbar-utility 3.3.0 
web-data 0.7.1 
web-lookup 1.3.1 
x-terminal 13.0.10 
```

**Comment by iamh2o** [comment]
i solved it by copyting a png to the missing img location
